<?php

namespace Tournament\Armor\Weapons\Swords;

use Tournament\Armor\ArmorSlots;
use Tournament\Armor\Weapons\Weapon;
use Tournament\GameMechanics\Damage;

class TwoHandSword  extends Weapon
{
    private $damageCount;

    public function __construct()
    {
        $this->slot = ArmorSlots::SLOT_RIGHT_HAND || ArmorSlots::SLOT_LEFT_HAND;
        $this->damage = 12;
    }

    public function handleDamage(Damage $dmg):Damage
    {
        $dmg =  parent::handleDamage($dmg); // TODO: Change the autogenerated stub
        $this->damageCount++;
        if ($this->damageCount % 3 == 0){
            $dmg->incrementDamage(-$this->damage);
        }
        return $dmg;
    }

}